apiVersion: apps/v1
kind: Deployment
metadata:
  name: climate-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: climate
  template:
    metadata:
      labels:
        app: climate
    spec:
      containers:
      - name: backend
        image: climate-backend:latest
        ports:
        - containerPort: 5000
      - name: frontend
        image: climate-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: climate-service
spec:
  type: LoadBalancer
  selector:
    app: climate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
