name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Run Tests
      run: |
        pytest backend/tests

    - name: Build Docker Images
      run: |
        docker build -t climate-backend ./backend
        docker build -t climate-frontend ./frontend

    - name: Push Docker Images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag climate-backend:latest ${{ secrets.DOCKER_USERNAME }}/climate-backend:latest
        docker tag climate-frontend:latest ${{ secrets.DOCKER_USERNAME }}/climate-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/climate-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/climate-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes_deployment.yaml
